[package]
name = "dashium"
version = "0.1.0"
edition = "2024"
description = "A Geometry Dash Private Server written in Rust"

[dependencies]
axum = "0.8.4"
anyhow = "1.0"
dotenvy = "0.15.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "macros",
] }
